apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-rollout

resources:
  - rollout/deployment.yaml
  - rollout/services.yaml
  - rollout/ingressroutes.yaml
  - resources/namespace.yaml
  - dashboard/deployment.yaml
  - dashboard/services.yaml

