apiVersion: v1
kind: Namespace
metadata:
  name: argocd-rollouts
  labels:
    name: argocd-rollouts
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-rollouts-dashboard
  labels:
    name: argocd-rollouts-dashboard