apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-rollouts

resources:
  - canary/deployment.yaml
  - canary/services.yaml
  - canary/ingressroutes.yaml
  - bluegreen/deployment.yaml
  - bluegreen/services.yaml
  - bluegreen/ingressroutes.yaml

